[book]
language = "en"
src = "src"
title = "Lens Book"

[output.html]
git-repository-url = "https://github.com/samply/lens/tree/develop/book"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/samply/lens/edit/develop/book/{path}"
