name: Build and Push Develop Image samply/lens

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    # Necessary after this repository was renamed from samply/lens-web-components to samply/lens
    permissions:
      contents: read
      packages: write
      pull-requests: read
      security-events: write
      statuses: read
    # This workflow defines how a samply docker image is built, tested and published.
    # Visit: https://github.com/samply/github-workflows/blob/main/.github/workflows/docker-ci.yml, for more information
    uses: samply/github-workflows/.github/workflows/docker-ci.yml@main
    with:
      image-name: "samply/lens"
      build-args: |
        TARGET_ENVIRONMENT=staging
      build-platforms: "linux/amd64"
      push-to: dockerhub
    # This passes the secrets from calling workflow to the called workflow
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
